site_name: My Study Note
nav:
  - Home: index.md
  - Golang:
      - 'Philosophy': './go-study/01-go-setup/01-philosophy.md'
      - 'Setting Up': './go-study/01-go-setup/setup-go-env.md'
      - 'Quick Start': './go-study/02-quick-start/get-started.md'
      - 'Basics':
          - 'Variable, Method, & Function': './go-study/03-basics/basics.md'
      - 'Collections':
          - 'Array': './go-study/04-collections/array.md'
          - 'Slices': './go-study/04-collections/slices.md'
          - 'Map': './go-study/04-collections/maps.md'
      - Interface:
          - Interfaces: './go-study/05-interface/interfaces.md'
          - Reflection: './go-study/05-interface/reflection.md'
      - Concurrency:
          - Goroutine: './go-study/07-concurrency/1-goroutine/overview.md'
      - Error Handling:
          - 'Error': './go-study/08-error/01-error.md'
  - Rust:
      - 'Setting Up': './rust-study/01-rust-setup/setup-rust-env.md'
      - 'Quick Start': './rust-study/02-quick-start/quick-start.md'
      - 'Programming Concepts':
          - 'Variable': './rust-study/03-programming-concepts/1-variable-and-mutability.md'
          - 'Data Types': './rust-study/03-programming-concepts/2-data-types.md'
          - 'Flow Controls': './rust-study/03-programming-concepts/3-flow-controls.md'
          - 'Collections': './rust-study/03-programming-concepts/4-collections.md'
      - 'Generics and Traits':
          - 'Generics': './rust-study/10-generic-type-traits-lifetimes/generics.md'
          - 'Traits': './rust-study/10-generic-type-traits-lifetimes/traits.md'
      - 'Concurrency':
          - Standard: './rust-study/15-concurrency/concurrency.md'
          - Tokio: './rust-study/15-concurrency/tokio-concurrency.md'
theme:
  name: material
  features:
    - content.code.annotate #
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.superfences:

plugins:
  - search