@startuml

entity "User" as u {
    + ID: int <<autoincrement>>
    --
    + Name: string
    + Email: string
    + Birthday: time.Time
    + CompanyID int <<FK>>
    + Company Company
    + CreatedAt: time.Time
    + UpdatedAt: time.Time
    + DeletedAt: time.Time
}

entity "Company" as c {
    + ID: int <<autoincrement>>
    --
    + Name: string
    + CreatedAt: time.Time
    + UpdatedAt: time.Time
    + DeletedAt: time.Time
}

u ||--|| c

@enduml