// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlgen

import (
	"database/sql"
	"time"
)

type Author struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

type Book struct {
	ID        int64
	Title     string
	AuthorID  int64
	Published time.Time
}
